4.1

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [3]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [7]:
%timeit my_arr2 = my_arr*2

750 μs ± 2.17 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
%timeit my_list2 = my_list*2

4.72 ms ± 8.41 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
#ndarray

In [10]:
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [11]:
data*data

array([[2.250e+00, 1.000e-02, 9.000e+00],
       [0.000e+00, 9.000e+00, 4.225e+01]])

In [12]:
data**2

array([[2.250e+00, 1.000e-02, 9.000e+00],
       [0.000e+00, 9.000e+00, 4.225e+01]])

In [13]:
data.shape

(2, 3)

In [14]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.shape

(2, 4)

In [17]:
arr2.dtype

dtype('int64')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.arange(12,dtype=np.float64)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [24]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
1/arr2

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [26]:
arr = np.arange(10)

In [27]:
arr[:4]

array([0, 1, 2, 3])

In [28]:
arr1 = arr[:4]
arr1

array([0, 1, 2, 3])

In [29]:
arr = np.arange(3,16)

In [30]:
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
arr1

array([0, 1, 2, 3])

In [32]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d[2]

array([7, 8, 9])

In [35]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr2d[2][1]

np.int64(8)

In [37]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr3d[0][0]

array([1, 2, 3])

In [40]:
arr3d[1][0][1]

np.int64(8)

In [41]:
names =np.array(['bob','joe','will','bob','will','joe','joe'])
data = np.array([[4,7],[0,2],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [42]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [43]:
names =='bob'

array([ True, False, False,  True, False, False, False])

In [44]:
data[names=='bob']

array([[4, 7],
       [0, 0]])

In [45]:
arr = np.zeros((8,4))

In [46]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
for i in range(8):
    arr[i]=i


arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [48]:
arr = np.arange(32).reshape((8,4))

In [49]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [50]:
np.dot(arr.T,arr)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])