In [1]:
import numpy as np
import pandas as pd

In [2]:
from pandas import Series,DataFrame

5.1 Intro to Data Structures
Series and DataFrames

Series

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj[1]

np.int64(7)

In [5]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,7,-5,3],index=['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2[['c','a']]

c    3
a   -5
dtype: int64

In [12]:
obj2[obj2<0]

a   -5
dtype: int64

In [13]:
obj2**2

d    16
b    49
a    25
c     9
dtype: int64

In [14]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
obj2['c']**obj2['c']

np.int64(27)

In [16]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [17]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [18]:
'Texas' in sdata

True

In [19]:
obj3 = pd.Series(sdata)

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
obj3.index

Index(['Ohio', 'Texas', 'Oregon', 'Utah'], dtype='object')

In [22]:
obj3['Utah']

np.int64(5000)

In [23]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [24]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [25]:
states = ['Cali','Ohio','Delaware','Oregon']
obj4 = pd.Series(sdata , index=states)

In [26]:
obj4

Cali            NaN
Ohio        35000.0
Delaware        NaN
Oregon      16000.0
dtype: float64

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
obj3+obj4

Cali            NaN
Delaware        NaN
Ohio        70000.0
Oregon      32000.0
Texas           NaN
Utah            NaN
dtype: float64

In [29]:
obj4.name = 'population'

In [30]:
obj4.index.name = 'state'

In [31]:
obj4

state
Cali            NaN
Ohio        35000.0
Delaware        NaN
Oregon      16000.0
Name: population, dtype: float64

Dataframes

In [32]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [33]:
frame = pd.DataFrame(data)

In [34]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [35]:
frame.head()
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [36]:
frame2 = pd.DataFrame(data,columns=['pop','year','state','debt'])

In [37]:
frame.state.to_dict()

{0: 'Ohio', 1: 'Ohio', 2: 'Ohio', 3: 'Nevada', 4: 'Nevada', 5: 'Nevada'}

In [38]:
frame2

pop  year   state debt
0  1.5  2000    Ohio  NaN
1  1.7  2001    Ohio  NaN
2  3.6  2002    Ohio  NaN
3  2.4  2001  Nevada  NaN
4  2.9  2002  Nevada  NaN
5  3.2  2003  Nevada  NaN

In [39]:
frame2.loc[2]

pop       3.6
year     2002
state    Ohio
debt      NaN
Name: 2, dtype: object

In [40]:
frame2['debt'] = [11,12,45,67,34,76]

In [41]:
frame2

pop  year   state  debt
0  1.5  2000    Ohio    11
1  1.7  2001    Ohio    12
2  3.6  2002    Ohio    45
3  2.4  2001  Nevada    67
4  2.9  2002  Nevada    34
5  3.2  2003  Nevada    76

In [42]:
val = pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])

In [43]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [44]:
frame2['debt'] = val

In [45]:
frame2

pop  year   state  debt
0  1.5  2000    Ohio   NaN
1  1.7  2001    Ohio   NaN
2  3.6  2002    Ohio   NaN
3  2.4  2001  Nevada   NaN
4  2.9  2002  Nevada   NaN
5  3.2  2003  Nevada   NaN

In [46]:
frame2['eastern'] = frame2['state']=='Ohio' #assign the return value of if state is equal to Ohio

In [47]:
frame2

pop  year   state  debt  eastern
0  1.5  2000    Ohio   NaN     True
1  1.7  2001    Ohio   NaN     True
2  3.6  2002    Ohio   NaN     True
3  2.4  2001  Nevada   NaN    False
4  2.9  2002  Nevada   NaN    False
5  3.2  2003  Nevada   NaN    False

In [48]:
del frame2['debt']

In [49]:
frame2

pop  year   state  eastern
0  1.5  2000    Ohio     True
1  1.7  2001    Ohio     True
2  3.6  2002    Ohio     True
3  2.4  2001  Nevada    False
4  2.9  2002  Nevada    False
5  3.2  2003  Nevada    False

In [50]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},"Nevada": {2001: 2.4, 2002: 2.9}}

In [51]:
frame3 = pd.DataFrame(populations)

In [52]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [53]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [54]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [55]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [56]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [57]:
obj = pd.Series(np.arange(3), index=['a','b','c'])

In [58]:
index = obj.index

In [59]:
index

Index(['a', 'b', 'c'], dtype='object')

In [60]:
index[1] = 'd' #indexes are immutable

TypeError: Index does not support mutable operations

In [ ]:
frame3

In [ ]:
frame3.columns

In [ ]:
'Ohio'in frame3.columns

In [61]:
frame3.index

Index([2000, 2001, 2002], dtype='int64', name='year')

In [62]:
labels = pd.Index(['foo','foo','boo','bar'])

5.2 Essential Functionality

In [63]:
obj = pd.Series([4.5,7.2,-5.4,3.6], index=['d','b','a','c'])

In [64]:
obj

d    4.5
b    7.2
a   -5.4
c    3.6
dtype: float64

In [65]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [67]:
obj2
#reindexed

a   -5.4
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [68]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [71]:
obj3 = obj3.reindex(np.arange(6),method='ffill')
#ffill means forward fills the value
obj3

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [74]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],columns=['Ohio','Texas','Cali'])

In [75]:
frame

Ohio  Texas  Cali
a     0      1     2
c     3      4     5
d     6      7     8

In [76]:
frame2 = frame.reindex(index=['a','b','c','d'])

In [77]:
frame2

Ohio  Texas  Cali
a   0.0    1.0   2.0
b   NaN    NaN   NaN
c   3.0    4.0   5.0
d   6.0    7.0   8.0

In [78]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [79]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [80]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [85]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c','d', 'e'])

In [86]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a','c', 'e','f','g'])

In [87]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [88]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [89]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [90]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [91]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [92]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [93]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [94]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})

In [95]:
df1

A
0  1
1  2

In [96]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [97]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [98]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [99]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [100]:
arr = np.arange(12).reshape((3,4))

In [101]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
arr[0]

array([0, 1, 2, 3])

In [103]:
arr[1]

array([4, 5, 6, 7])

In [104]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),index=['Utah','Ohio','Texas', 'Oregon'])

In [105]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [106]:
series = frame.iloc[0]

In [107]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [108]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [109]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    1.305702  1.330835 -0.219664
Ohio    0.209628 -1.477292  0.209616
Texas   0.198197  1.901931  1.521401
Oregon  2.884030 -0.451050 -0.345519

In [110]:
np.abs(frame)

b         d         e
Utah    1.305702  1.330835  0.219664
Ohio    0.209628  1.477292  0.209616
Texas   0.198197  1.901931  1.521401
Oregon  2.884030  0.451050  0.345519

In [111]:
obj = pd.Series(np.arange(4), index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [113]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

5.3 Summarizing and Compting Descriptive Statistics

In [114]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=['a','b','c', 'd'],columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [115]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [116]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [117]:
df.idxmax()

one    b
two    d
dtype: object

In [118]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [119]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000